#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  May 15, 2019 11:05:34 AM +0300  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 615x519+353+136
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1684 1032
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure Frame -background #d9d9d9
    ttk::style configure Frame -foreground #000000
    ttk::style configure Frame -font "TkDefaultFont"
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 355 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 595 
    vTcl:DefineAlias "$top.fra43" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    listbox $site_3_0.lis48 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -height 102 -highlightbackground {#d9d9d9} \
        -highlightcolor black -selectbackground {#c4c4c4} \
        -selectforeground black -width 114 -listvariable lst2 
    .top42.fra43.lis48 configure -font "TkFixedFont"
    .top42.fra43.lis48 insert end text
    vTcl:DefineAlias "$site_3_0.lis48" "list_enemy2" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis49 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -height 102 -highlightbackground {#d9d9d9} \
        -highlightcolor black -selectbackground {#c4c4c4} \
        -selectforeground black -width 114 -listvariable lst3 
    .top42.fra43.lis49 configure -font "TkFixedFont"
    .top42.fra43.lis49 insert end text
    vTcl:DefineAlias "$site_3_0.lis49" "list_enemy1" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis50 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -height 102 -highlightbackground {#d9d9d9} \
        -highlightcolor black -selectbackground {#c4c4c4} \
        -selectforeground black -width 114 -listvariable lst1 
    .top42.fra43.lis50 configure -font "TkFixedFont"
    .top42.fra43.lis50 insert end text
    vTcl:DefineAlias "$site_3_0.lis50" "list_enemy3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lis48 \
        -in $site_3_0 -x 240 -y 10 -width 114 -relwidth 0 -height 102 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lis49 \
        -in $site_3_0 -x 440 -y 10 -width 114 -relwidth 0 -height 102 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lis50 \
        -in $site_3_0 -x 40 -y 10 -width 114 -relwidth 0 -height 102 \
        -relheight 0 -anchor nw -bordermode ignore 
    button $top.but44 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command stop -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Finished Turn} 
    vTcl:DefineAlias "$top.but44" "bnt_finish" vTcl:WidgetProc "Toplevel1" 1
    listbox $top.lis46 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -height 72 -highlightbackground {#d9d9d9} \
        -highlightcolor black -selectbackground {#c4c4c4} \
        -selectforeground black -width 164 -listvariable my_lst 
    .top42.lis46 configure -font "TkFixedFont"
    .top42.lis46 insert end text
    vTcl:DefineAlias "$top.lis46" "list_cards" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command pick -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Pick Card} 
    vTcl:DefineAlias "$top.but47" "bnt_pick" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 10 -y 10 -width 595 -relwidth 0 -height 355 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but44 \
        -in $top -x 20 -y 380 -width 99 -relwidth 0 -height 73 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lis46 \
        -in $top -x 230 -y 380 -width 164 -relwidth 0 -height 72 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 500 -y 380 -width 99 -relwidth 0 -height 73 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

